import { createServer } from 'node:http';
import { DatabaseSync } from 'node:sqlite';
import { randomBytes, scryptSync, timingSafeEqual, createHash } from 'node:crypto';
import { readFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const root=dirname(fileURLToPath(import.meta.url));
const dbPath=process.env.DB_PATH || resolve(root,'data/training.db');
mkdirSync(dirname(dbPath),{recursive:true});
const db=new DatabaseSync(dbPath);
db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('trainer','learner')));
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id INTEGER REFERENCES users(id),expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS courses(id INTEGER PRIMARY KEY,owner INTEGER REFERENCES users(id),title TEXT NOT NULL,category TEXT NOT NULL,description TEXT NOT NULL,minutes INTEGER NOT NULL,content TEXT NOT NULL,video TEXT NOT NULL,published INTEGER NOT NULL DEFAULT 0,pass INTEGER NOT NULL DEFAULT 80,questions TEXT NOT NULL DEFAULT '[]',revision INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS progress(user_id INTEGER REFERENCES users(id),course_id INTEGER REFERENCES courses(id),completed INTEGER NOT NULL DEFAULT 0,notes TEXT NOT NULL DEFAULT '',PRIMARY KEY(user_id,course_id));
CREATE TABLE IF NOT EXISTS attempts(id INTEGER PRIMARY KEY,user_id INTEGER REFERENCES users(id),course_id INTEGER REFERENCES courses(id),score INTEGER NOT NULL,passed INTEGER NOT NULL,answers TEXT NOT NULL,created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,revision INTEGER NOT NULL);
`);
const hash = p => {const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(p,salt,64).toString('hex');};
const verify = (p,h) => {const [salt,value]=h.split(':');return timingSafeEqual(scryptSync(p,salt,64),Buffer.from(value,'hex'));};
const digest = t=>createHash('sha256').update(t).digest('hex');
const publicUser=u=>({id:u.id,name:u.name,email:u.email,role:u.role});
const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
const str=(v,max=10000)=>typeof v==='string'?v.trim().slice(0,max):'';
const attemptsByIp=new Map();
function youtube(value){if(!value)return '';let u;try{u=new URL(value);}catch{fail(400,'Ingresa un enlace válido de YouTube.');}if(u.protocol!=='https:')fail(400,'Usa un enlace HTTPS de YouTube.');let id='';if(['youtube.com','www.youtube.com','m.youtube.com'].includes(u.hostname))id=u.searchParams.get('v')||u.pathname.match(/^\/(?:embed|shorts|live)\/([^/]+)/)?.[1];if(u.hostname==='youtu.be')id=u.pathname.slice(1);if(!/^[\w-]{11}$/.test(id||''))fail(400,'El enlace de YouTube no es válido.');return id;}
async function body(req){let value='';for await(const chunk of req){value+=chunk;if(Buffer.byteLength(value)>300000)fail(413,'El contenido es demasiado grande.');}try{return JSON.parse(value||'{}');}catch{fail(400,'Solicitud inválida.');}}
function seed(owner){for(const [title,category,description,content,minutes] of [
['Tu primera llamada, paso a paso','Inducción','Conoce la estructura de una llamada y empieza con seguridad.','1. Saluda con tu nombre y el de la empresa.\n2. Escucha el motivo de la llamada sin interrumpir.\n3. Confirma lo que entendiste.\n4. Resuelve o escala según el proceso de tu campaña.\n5. Resume los acuerdos y agradece el tiempo del cliente.',20],
['Escucha activa y empatía','Habilidades','Transforma conversaciones difíciles en una atención cercana.','Deja que el cliente termine de explicar su situación. Confirma su necesidad con tus propias palabras.\n\nEvita prometer resultados que no puedes garantizar. Explica el siguiente paso con claridad y confirma que el cliente lo comprendió.',25],
['Protección de datos del cliente','Calidad','Aplica buenas prácticas al consultar y registrar información.','Verifica la identidad según el protocolo de tu campaña antes de compartir información.\n\nNo copies datos del cliente a cuentas personales. Bloquea tu sesión al ausentarte y reporta cualquier incidente por el canal interno.',15]
])db.prepare('INSERT INTO courses(owner,title,category,description,minutes,content,video,published,questions) VALUES(?,?,?,?,?,?,?,?,?)').run(owner,title,category,description,minutes,content,'',1,JSON.stringify([{text:category==='Calidad'?'¿Qué debes hacer antes de compartir información del cliente?':'¿Qué debes hacer antes de proponer una solución?',options:category==='Calidad'?['Verificar la identidad según el protocolo','Copiar los datos a tu correo personal','Compartirlos sin verificación']:['Confirmar la necesidad del cliente','Interrumpir para reducir el tiempo','Prometer cualquier resultado'],correct:0}])) ;}
export const server=createServer(async(req,res)=>{
const url=new URL(req.url,'http://localhost');const path=url.pathname;
res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; frame-src https://www.youtube-nocookie.com; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'");
const json=(data,status=200)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
try{
if(!path.startsWith('/api/')){if(req.method!=='GET')fail(405,'Método no permitido.');const files={'/':'index.html','/index.html':'index.html','/app.js':'app.js','/styles.css':'styles.css'};if(!files[path])fail(404,'No encontrado.');res.setHeader('Content-Type',path.endsWith('.js')?'text/javascript; charset=utf-8':path.endsWith('.css')?'text/css; charset=utf-8':'text/html; charset=utf-8');res.end(readFileSync(resolve(root,files[path])));return;}
if(!['GET','POST','PUT'].includes(req.method))fail(405,'Método no permitido.');
if(req.method!=='GET'){const origin=req.headers.origin;if(origin&&origin!==`${req.socket.encrypted?'https':'http'}://${req.headers.host}`&&origin!==process.env.APP_ORIGIN)fail(403,'Origen no permitido.');if(!req.headers['content-type']?.startsWith('application/json'))fail(415,'Se requiere JSON.');}
const token=req.headers.cookie?.match(/(?:^|;\s*)session=([a-f0-9]{64})(?:;|$)/)?.[1];
const user=token?db.prepare('SELECT u.* FROM users u JOIN sessions s ON s.user_id=u.id WHERE s.token=? AND s.expires>?').get(digest(token),Date.now()):null;
if(path==='/api/session'&&req.method==='GET')return json({user:user?publicUser(user):null,needsSetup:!db.prepare('SELECT id FROM users LIMIT 1').get()});
if(['/api/setup','/api/login','/api/register'].includes(path)&&req.method==='POST'){
const ip=req.socket.remoteAddress;const rate=attemptsByIp.get(ip)||{count:0,until:Date.now()+900000};if(rate.until<Date.now()){rate.count=0;rate.until=Date.now()+900000;}rate.count++;attemptsByIp.set(ip,rate);if(rate.count>30)fail(429,'Demasiados intentos. Intenta en 15 minutos.');
const b=await body(req),email=str(b.email,200).toLowerCase(),password=typeof b.password==='string'?b.password:'';if(password.length>200)fail(400,'Contraseña demasiado larga.');let account;
if(path==='/api/login'){account=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!account||!verify(password,account.password))fail(401,'Correo o contraseña incorrectos.');if(b.portal && b.portal!==account.role)fail(403,account.role==='trainer'?'Tu cuenta es de capacitador. Selecciona ese acceso.':'Tu cuenta es de participante. Selecciona ese acceso.');}
else {if(path==='/api/setup'&&db.prepare('SELECT id FROM users LIMIT 1').get())fail(403,'La cuenta principal ya está configurada.');if(path==='/api/register'&&!db.prepare('SELECT id FROM users LIMIT 1').get())fail(400,'Primero configura el capacitador.');if(!str(b.name,100)||!/^\S+@\S+\.\S+$/.test(email)||password.length<10)fail(400,'Escribe tu nombre, un correo válido y una contraseña de al menos 10 caracteres.');if(db.prepare('SELECT id FROM users WHERE email=?').get(email))fail(409,'Este correo ya está registrado.');const role=path==='/api/setup'?'trainer':'learner';const result=db.prepare('INSERT INTO users(name,email,password,role) VALUES(?,?,?,?)').run(str(b.name,100),email,hash(password),role);account=db.prepare('SELECT * FROM users WHERE id=?').get(result.lastInsertRowid);if(role==='trainer')seed(account.id);}
const session=randomBytes(32).toString('hex');db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now());db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(digest(session),account.id,Date.now()+86400000);res.setHeader('Set-Cookie',`session=${session}; HttpOnly; SameSite=Lax; Path=/; Max-Age=86400${process.env.APP_ORIGIN?.startsWith('https:')?'; Secure':''}`);return json({user:publicUser(account)});}
if(!user)fail(401,'Inicia sesión para continuar.');
if(path==='/api/logout'&&req.method==='POST'){db.prepare('DELETE FROM sessions WHERE token=?').run(digest(token));res.setHeader('Set-Cookie','session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0');return json({ok:true});}
if(path==='/api/courses'&&req.method==='GET'){const courses=db.prepare('SELECT c.*,u.name AS trainer FROM courses c JOIN users u ON u.id=c.owner WHERE c.published=1 OR c.owner=? ORDER BY c.id DESC').all(user.id).map(c=>{const q=JSON.parse(c.questions);return {...c,questions:user.role==='trainer'&&c.owner===user.id?q:q.map(({correct,...rest})=>rest),progress:db.prepare('SELECT completed,notes FROM progress WHERE user_id=? AND course_id=?').get(user.id,c.id)||{completed:0,notes:''},attempts:db.prepare('SELECT id,score,passed,created,revision FROM attempts WHERE user_id=? AND course_id=? ORDER BY id DESC').all(user.id,c.id)};});return json({courses});}
if(path==='/api/dashboard'&&req.method==='GET'){
  if(user.role!=='trainer')fail(403,'Este panel es exclusivo del capacitador.');
  const learners=db.prepare("SELECT id,name,email FROM users WHERE role='learner' ORDER BY name").all();
  const courses=db.prepare('SELECT id,title,published,revision,category FROM courses WHERE owner=? ORDER BY id DESC').all(user.id);
  const rows=db.prepare(`SELECT a.* FROM attempts a JOIN courses c ON c.id=a.course_id JOIN users u ON u.id=a.user_id WHERE c.owner=? AND u.role='learner' ORDER BY a.id DESC`).all(user.id);
  const progressRows=db.prepare('SELECT p.user_id,p.course_id,p.completed FROM progress p JOIN courses c ON c.id=p.course_id WHERE c.owner=?').all(user.id);
  const active=courses.filter(c=>c.published);
  const learnerProgress=learners.map(u=>({...u,courses:active.map(c=>{
    const attempts=rows.filter(a=>a.user_id===u.id&&a.course_id===c.id&&a.revision===c.revision);
    const latest=attempts[0];
    const passed=attempts.some(a=>a.passed);
    const completed=Boolean(progressRows.find(p=>p.user_id===u.id&&p.course_id===c.id)?.completed);
    return {id:c.id,title:c.title,score:latest?.score??null,attempts:attempts.length,status:passed?'passed':latest?'retry':completed?'ready':'pending'};
  })}));
  const summary=courses.map(c=>{const entries=learnerProgress.flatMap(u=>u.courses.filter(p=>p.id===c.id));return {...c,participants:c.published?learners.length:0,passed:entries.filter(e=>e.status==='passed').length,pending:entries.filter(e=>e.status!=='passed').length};});
  const entries=learnerProgress.flatMap(u=>u.courses);
  return json({courses:summary,learners:learnerProgress,stats:{learners:learners.length,published:active.length,drafts:courses.length-active.length,passed:entries.filter(e=>e.status==='passed').length,pending:entries.filter(e=>e.status!=='passed').length,retry:entries.filter(e=>e.status==='retry').length},recent:rows.slice(0,6).map(a=>({id:a.id,name:learners.find(u=>u.id===a.user_id)?.name,title:courses.find(c=>c.id===a.course_id)?.title,score:a.score,passed:a.passed,created:a.created}))});
}
if(path==='/api/team'&&req.method==='GET'){if(user.role!=='trainer')fail(403,'Acceso solo para capacitadores.');return json({users:db.prepare('SELECT id,name,email,role FROM users ORDER BY name').all(),results:db.prepare('SELECT a.id,a.score,a.passed,a.created,c.title,u.name,u.email FROM attempts a JOIN courses c ON c.id=a.course_id JOIN users u ON u.id=a.user_id WHERE c.owner=? ORDER BY a.id DESC').all(user.id)});}
if(path.match(/^\/api\/team\/\d+$/)&&req.method==='PUT'){if(user.role!=='trainer')fail(403,'Sin permiso.');const id=Number(path.split('/').pop());if(id===user.id)fail(400,'No puedes cambiar tu propio rol.');const b=await body(req);if(!['trainer','learner'].includes(b.role))fail(400,'Rol inválido.');db.prepare('UPDATE users SET role=? WHERE id=?').run(b.role,id);return json({ok:true});}
if(path==='/api/courses'&&req.method==='POST'||/^\/api\/courses\/\d+$/.test(path)&&req.method==='PUT'){
if(user.role!=='trainer')fail(403,'Solo los capacitadores pueden crear contenido.');const id=req.method==='PUT'?Number(path.split('/').pop()):null;const old=id?db.prepare('SELECT * FROM courses WHERE id=? AND owner=?').get(id,user.id):null;if(id&&!old)fail(404,'Capacitación no encontrada.');const b=await body(req);if(!str(b.title,150)||!str(b.content,50000))fail(400,'Agrega un título y contenido para estudiar.');if(!Number.isInteger(b.minutes)||b.minutes<1||b.minutes>1000||!Number.isInteger(b.pass)||b.pass<1||b.pass>100)fail(400,'Revisa la duración y la nota mínima.');if(!Array.isArray(b.questions)||b.questions.length>50)fail(400,'La prueba admite hasta 50 preguntas.');const questions=b.questions.map(q=>{if(!str(q.text,1000)||!Array.isArray(q.options)||q.options.length<2||q.options.length>6||q.options.some(o=>!str(o,500))||!Number.isInteger(q.correct)||q.correct<0||q.correct>=q.options.length)fail(400,'Cada pregunta necesita opciones y una respuesta correcta.');return {text:str(q.text,1000),options:q.options.map(o=>str(o,500)),correct:q.correct};});if(b.published&&!questions.length)fail(400,'Agrega al menos una pregunta antes de publicar.');const fields=[str(b.title,150),str(b.category,80)||'General',str(b.description,600),b.minutes,str(b.content,50000),youtube(str(b.video,500)),b.published?1:0,b.pass,JSON.stringify(questions)];let result;if(id){const revision=old.revision+(old.questions!==JSON.stringify(questions)||old.pass!==b.pass?1:0);db.prepare('UPDATE courses SET title=?,category=?,description=?,minutes=?,content=?,video=?,published=?,pass=?,questions=?,revision=? WHERE id=?').run(...fields,revision,id);}else result=db.prepare('INSERT INTO courses(title,category,description,minutes,content,video,published,pass,questions,owner) VALUES(?,?,?,?,?,?,?,?,?,?)').run(...fields,user.id);return json({id:id||Number(result.lastInsertRowid)});}
const match=path.match(/^\/api\/courses\/(\d+)\/(progress|attempt)$/);if(match&&req.method==='POST'){if(user.role!=='learner')fail(403,'Solo los participantes registran avances y resuelven evaluaciones. Usa la vista previa para revisar tu contenido.');const c=db.prepare('SELECT * FROM courses WHERE id=? AND published=1').get(Number(match[1]));if(!c)fail(404,'Capacitación no disponible.');const b=await body(req);if(match[2]==='progress'){const prev=db.prepare('SELECT * FROM progress WHERE user_id=? AND course_id=?').get(user.id,c.id);db.prepare('INSERT INTO progress(user_id,course_id,completed,notes) VALUES(?,?,?,?) ON CONFLICT(user_id,course_id) DO UPDATE SET completed=excluded.completed,notes=excluded.notes').run(user.id,c.id,b.completed===undefined?(prev?.completed||0):(b.completed?1:0),b.notes===undefined?(prev?.notes||''):str(b.notes,10000));return json({ok:true});}
const questions=JSON.parse(c.questions);if(b.revision!==c.revision)fail(409,'La prueba cambió. Vuelve a abrir la capacitación.');if(!questions.length||!Array.isArray(b.answers)||b.answers.length!==questions.length||b.answers.some((a,i)=>!Number.isInteger(a)||a<0||a>=questions[i].options.length))fail(400,'Responde todas las preguntas.');const score=Math.round(questions.filter((q,i)=>q.correct===b.answers[i]).length/questions.length*100);const passed=score>=c.pass;db.prepare('INSERT INTO attempts(user_id,course_id,score,passed,answers,revision) VALUES(?,?,?,?,?,?)').run(user.id,c.id,score,passed?1:0,JSON.stringify(b.answers),c.revision);return json({score,passed,correct:questions.filter((q,i)=>q.correct===b.answers[i]).length,total:questions.length});}
fail(404,'No encontrado.');
}catch(e){if(!e.status)console.error(e);json({error:e.status?e.message:'No se pudo completar la operación. Intenta nuevamente.'},e.status||500);}
});
if(process.env.NODE_ENV!=='test')server.listen(Number(process.env.PORT)||3000,process.env.HOST||'127.0.0.1',()=>console.log(`Innovatek disponible en http://${process.env.HOST||'127.0.0.1'}:${process.env.PORT||3000}`));

