import test from 'node:test';
import assert from 'node:assert/strict';
import { createDemoApi } from '../demo/local-api.mjs';
const memory = () => { const data = new Map(); return { getItem: key => data.get(key) ?? null, setItem: (key, value) => data.set(key, String(value)), removeItem: key => data.delete(key) }; };
test('Pages demo persists courses, notes and versioned results across profiles and reloads', async () => {
  const storage = memory(), session = memory();
  let api = createDemoApi(storage, session);
  assert.equal((await api('/session')).user, null);
  await api('/login', 'POST', { id: 1 });
  const course = { title: 'Curso de prueba', description: 'Ejemplo', category: 'Prueba', minutes: 10, content: 'Material', video: '', pass: 80, published: true, questions: [{ text: 'Elige A', options: ['A', 'B'], correct: 0 }] };
  const { id } = await api('/courses', 'POST', course);
  await api('/logout', 'POST');
  await api('/login', 'POST', { id: 2 });
  await api(`/courses/${id}/progress`, 'POST', { completed: true, notes: 'Mi nota' });
  assert.equal((await api(`/courses/${id}/attempt`, 'POST', { revision: 1, answers: [0] })).score, 100);
  api = createDemoApi(storage, session);
  let saved = (await api('/courses')).courses.find(c => c.id === id);
  assert.equal(saved.progress.notes, 'Mi nota');
  assert.equal(saved.attempts[0].passed, true);
  assert.equal(saved.questions[0].correct, undefined);
  await api('/login', 'POST', { id: 3 });
  saved = (await api('/courses')).courses.find(c => c.id === id);
  assert.equal(saved.progress.notes, '');
  assert.equal(saved.attempts.length, 0);
  await assert.rejects(api('/courses', 'POST', course));
  await api('/login', 'POST', { id: 1 });
  let dashboard = await api('/dashboard');
  assert.equal(dashboard.learners.find(u => u.id === 2).courses.find(c => c.id === id).status, 'passed');
  assert.equal(dashboard.learners.find(u => u.id === 3).courses.find(c => c.id === id).status, 'pending');
  course.questions[0].correct = 1;
  await api(`/courses/${id}`, 'PUT', course);
  dashboard = await api('/dashboard');
  assert.equal(dashboard.learners.find(u => u.id === 2).courses.find(c => c.id === id).status, 'ready');
  await api('/login', 'POST', { id: 2 });
  await assert.rejects(api(`/courses/${id}/attempt`, 'POST', { revision: 1, answers: [0] }), /cambió/);
  await assert.rejects(api(`/courses/${id}/attempt`, 'POST', { revision: 2, answers: [9] }), /Responde/);
  assert.equal((await api(`/courses/${id}/attempt`, 'POST', { revision: 2, answers: [1] })).passed, true);
  assert.equal((await createDemoApi(memory(), memory())('/session')).user, null);
});
test('Pages demo reports storage failure without reporting a successful save', async () => {
  const storage = { getItem: () => null, setItem: () => { throw Error('Quota'); } };
  const api = createDemoApi(storage, memory());
  await assert.rejects(api('/login', 'POST', { id: 1 }), /guardar/);
});

test('demo supports user creation and permission changes without storing passwords', async () => {
  const storage=memory(), session=memory(), api=createDemoApi(storage,session);
  const admin=(await api('/login','POST',{id:1})).user;
  assert.equal(admin.accessLevel,'admin');
  const author=(await api('/team','POST',{name:'Autor',email:'author@example.invalid',password:'do-not-store',accessLevel:'trainer',permissions:['courses.manage']})).user;
  assert.equal(storage.getItem('innovacampus-pages-demo-v1').includes('do-not-store'),false);
  await api('/login','POST',{id:author.id});
  await assert.rejects(api('/team','POST',{name:'Intruso',email:'no@example.invalid',accessLevel:'admin'}));
  await assert.rejects(api('/dashboard'));
  const draft={title:'Borrador',content:'Material',minutes:10,pass:80,questions:[],published:false};
  await api('/courses','POST',draft);
  await assert.rejects(api('/courses','POST',{...draft,published:true}));
  await api('/login','POST',{id:1});
  await api('/team/'+author.id,'PUT',{accessLevel:'advisor',permissions:[]});
  const advisor=(await api('/login','POST',{id:author.id})).user;
  assert.equal(advisor.role,'learner');assert.equal(advisor.accessLevel,'advisor');
});
