import { readFileSync, writeFileSync, mkdirSync, copyFileSync, cpSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../', import.meta.url));
const output = resolve(root, 'docs');
mkdirSync(output, { recursive: true });
cpSync(resolve(root, 'client'), resolve(output, 'client'), { recursive: true });
let app = readFileSync(resolve(root, 'client/views/campus-view.js'), 'utf8');
app = app.replaceAll('Solo tú puedes ver estas notas.', 'Estas notas pertenecen al perfil de ejemplo seleccionado.');
app = app.replaceAll('La respuesta correcta solo es visible para ti, como autor de esta capacitación.', 'Esta vista muestra la clave de respuestas de la demostración.');
app = app.replaceAll('Los participantes crean su cuenta. Puedes habilitarlos como capacitadores.', 'Puedes cambiar el rol de los perfiles de ejemplo de este navegador.');
app = app.replaceAll('Los participantes crean su cuenta.', 'Los perfiles de ejemplo comparten este navegador.');
app = app.replace('<label>Contraseña inicial<input name="password" type="password" required minlength="10" maxlength="200" autocomplete="new-password"><small>Mínimo 10 caracteres. Comparte las credenciales de forma privada.</small></label>', '<p class="field-help">Crea solo perfiles de prueba. La demo no usa contraseñas y cualquier persona en este navegador puede seleccionar estos perfiles.</p>');
app = app.replace('href="/"', 'href="./"');
app = app.replace('<span>Cerrar sesión</span>', '<span>Cambiar perfil</span>');
writeFileSync(resolve(output, 'client/views/campus-view.js'), app);
writeFileSync(resolve(output, 'app.js'), `import { startCampus } from './client/controllers/campus-controller.js';
import { createDemoApi, renderDemoLogin } from './local-api.mjs';
await startCampus({api: createDemoApi(localStorage, sessionStorage), authView: renderDemoLogin});
`);
let html = readFileSync(resolve(root, 'views/index.html'), 'utf8');
html = html.replace('<body>', '<body><aside class="demo-banner" aria-label="Modo demostración"><strong>DEMO · GitHub Pages</strong><span>Datos de prueba guardados solo en este navegador. No se sincronizan y se pierden al borrar los datos del sitio.</span></aside>');
html = html.replace('</head>', '<link rel="stylesheet" href="demo.css"></head>');
writeFileSync(resolve(output, 'index.html'), html);
copyFileSync(resolve(root, 'styles.css'), resolve(output, 'styles.css'));
copyFileSync(resolve(root, 'navigation.css'), resolve(output, 'navigation.css'));
writeFileSync(resolve(output, 'local-api.mjs'), readFileSync(resolve(root, 'demo/local-api.mjs'), 'utf8').replace("from '../access.mjs'", "from './access.mjs'"));
copyFileSync(resolve(root, 'access.mjs'), resolve(output, 'access.mjs'));
copyFileSync(resolve(root, 'demo/demo.css'), resolve(output, 'demo.css'));
writeFileSync(resolve(output, '.nojekyll'), '');
console.log('Demostración generada en docs/');
