import { db } from './database.mjs';

// SQL and persistence are private to the model layer.
export const repository = {
  firstUser: (...args) => db.prepare('SELECT id FROM users LIMIT 1').get(...args),
  userByEmail: (...args) => db.prepare('SELECT * FROM users WHERE email=?').get(...args),
  userIdByEmail: (...args) => db.prepare('SELECT id FROM users WHERE email=?').get(...args),
  createUser: (...args) => db.prepare('INSERT INTO users(name,email,password,role) VALUES(?,?,?,?)').run(...args),
  setAccessLevel: (...args) => db.prepare('UPDATE users SET access_level=? WHERE id=?').run(...args),
  userById: (...args) => db.prepare('SELECT * FROM users WHERE id=?').get(...args),
  deleteExpiredSessions: (...args) => db.prepare('DELETE FROM sessions WHERE expires<?').run(...args),
  createSession: (...args) => db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(...args),
  deleteSession: (...args) => db.prepare('DELETE FROM sessions WHERE token=?').run(...args),
  visibleCourses: (...args) => db.prepare('SELECT c.*,u.name AS trainer FROM courses c JOIN users u ON u.id=c.owner WHERE c.published=1 OR c.owner=? ORDER BY c.id DESC').all(...args),
  courseProgress: (...args) => db.prepare('SELECT completed,notes FROM progress WHERE user_id=? AND course_id=?').get(...args),
  courseAttempts: (...args) => db.prepare('SELECT id,score,passed,created,revision FROM attempts WHERE user_id=? AND course_id=? ORDER BY id DESC').all(...args),
  ownedCourse: (...args) => db.prepare('SELECT * FROM courses WHERE id=? AND owner=?').get(...args),
  updateCourse: (...args) => db.prepare('UPDATE courses SET title=?,category=?,description=?,minutes=?,content=?,video=?,published=?,pass=?,questions=?,revision=? WHERE id=?').run(...args),
  createCourse: (...args) => db.prepare('INSERT INTO courses(title,category,description,minutes,content,video,published,pass,questions,owner) VALUES(?,?,?,?,?,?,?,?,?,?)').run(...args),
  publishedCourse: (...args) => db.prepare('SELECT * FROM courses WHERE id=? AND published=1').get(...args),
  progressRecord: (...args) => db.prepare('SELECT * FROM progress WHERE user_id=? AND course_id=?').get(...args),
  saveProgress: (...args) => db.prepare('INSERT INTO progress(user_id,course_id,completed,notes) VALUES(?,?,?,?) ON CONFLICT(user_id,course_id) DO UPDATE SET completed=excluded.completed,notes=excluded.notes').run(...args),
  createAttempt: (...args) => db.prepare('INSERT INTO attempts(user_id,course_id,score,passed,answers,revision) VALUES(?,?,?,?,?,?)').run(...args),
  learners: (...args) => db.prepare("SELECT id,name,email FROM users WHERE role='learner' ORDER BY name").all(...args),
  ownedCourseSummaries: (...args) => db.prepare('SELECT id,title,published,revision,category FROM courses WHERE owner=? ORDER BY id DESC').all(...args),
  ownedLearnerAttempts: (...args) => db.prepare(`SELECT a.* FROM attempts a JOIN courses c ON c.id=a.course_id JOIN users u ON u.id=a.user_id WHERE c.owner=? AND u.role='learner' ORDER BY a.id DESC`).all(...args),
  ownedProgress: (...args) => db.prepare('SELECT p.user_id,p.course_id,p.completed FROM progress p JOIN courses c ON c.id=p.course_id WHERE c.owner=?').all(...args),
  users: (...args) => db.prepare('SELECT * FROM users ORDER BY name').all(...args),
  teamResults: (...args) => db.prepare('SELECT a.id,a.score,a.passed,a.created,c.title,u.name,u.email FROM attempts a JOIN courses c ON c.id=a.course_id JOIN users u ON u.id=a.user_id WHERE c.owner=? ORDER BY a.id DESC').all(...args),
  sessionUser: (...args) => db.prepare('SELECT u.* FROM users u JOIN sessions s ON s.user_id=u.id WHERE s.token=? AND s.expires>?').get(...args),
  updateUserAccess: (...args) => db.prepare('UPDATE users SET role=?,access_level=?,permissions=? WHERE id=?').run(...args),
  deleteUserSessions: (...args) => db.prepare('DELETE FROM sessions WHERE user_id=?').run(...args),
  createManagedUser: (...args) => db.prepare('INSERT INTO users(name,email,password,role,access_level,permissions) VALUES(?,?,?,?,?,?)').run(...args),
};
